name = "TailBliss"
license = "Apache-2.0"
licenselink = "https://github.com/nusserstudios/tailbliss/blob/main/LICENSE"
description = "An innovative solution for Modern Medical Laboratories, Patients and Companies, revolutionizing Medical Lab test experience."

# The home page of the theme, where the source can be found.
homepage = "https://github.com/ukane-philemon/labtracka"

# If you have a running demo of the theme.
demosite = "https://tailbliss.netlify.app/"

tags = ["labtracka", "medical laboratories", "lab results", "lab LMS"]

min_version = "0.104.0"

# If the theme has a single author
[author]
    name = "Philemon Ukane"
    # homepage = "https://nusserstudios.com"

# If porting an existing theme
[original]
  name = "Hugo-Tailwind-3.1"
  author = "4044ever"
  homepage = "https://github.com/4044ever"
  repo = "https://github.com/4044ever/Hugo-Tailwind-3.1"